---
language: ruby

services:
  - docker

before_install:
  - docker pull robertdebock/docker-revealmd

script:
  - bundle exec rake test
  - for file in *.md ; do reveal-md "${file}" --static output/"${file%.*}" ; done

deploy:
  provider: pages
  local-dir: output
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
