language: node_js
node_js:
  - "6.1"

install:
  - apt-cache update && apt-get upgrade
  - npm install -g reveal-md

script:
  - for file in *.md ; do reveal-md "${file}" --static output/"${file%.*}" ; done
  
deploy:
  provider: pages
  local-dir: output
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
